local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, 244)
combat:setParameter(COMBAT_PARAM_AGGRESSIVE, false)

local skill = Condition(CONDITION_ATTRIBUTES)
skill:setParameter(CONDITION_PARAM_SUBID, 6)
skill:setParameter(CONDITION_PARAM_TICKS, 40000)
skill:setParameter(CONDITION_PARAM_STAT_MAGICPOINTS, 25)
skill:setParameter(CONDITION_PARAM_DISABLE_DEFENSE, true)
skill:setParameter(CONDITION_PARAM_BUFF_SPELL, true)
skill:setParameter(CONDITION_PARAM_SKILL_CRITICAL_HIT_CHANCE, 15)
skill:setParameter(CONDITION_PARAM_SKILL_CRITICAL_HIT_DAMAGE, 20)
skill:setParameter(CONDITION_PARAM_BUFF_DAMAGERECEIVED, 85)
combat:addCondition(skill)

local outfit = Condition(CONDITION_OUTFIT)
outfit:setParameter(CONDITION_PARAM_TICKS, 40000)
outfit:setOutfit({lookType = 1596})
combat:addCondition(outfit)

local spell = Spell("instant")

function spell.onCastSpell(creature, variant)
    return combat:execute(creature, variant)
end

spell:name("Avatar of Light")
spell:words("uteta res dru")
spell:group("support")
spell:vocation("druid;true", "elder druid;true")
spell:id(135)
spell:cooldown(5 * 1000)
spell:groupCooldown(10 * 60 * 1000)
spell:level(300)
spell:mana(2200)
spell:isSelfTarget(true)
spell:isAggressive(false)
spell:isPremium(true)
spell:needLearn(false)
spell:register()
